### ISSUE TITLE
Getting class requires API 24 even after using this

### ISSUE THREAD

**Issue by android-bash** [SgtSilvio/android-retrofix#1]
I have set up this library as given in READMe File. Also i have my code like below : 

            mClient.toAsync().subscribeWith()
                            .topicFilter(topic)
                            .qos(MqttQos.EXACTLY_ONCE)
                            .send()
                            .whenComplete((subAck, throwable) -> {
                                if (throwable == null) {
                                    Log.e(HiveMqttService.class.getSimpleName(), " topic 
           successfully");
                                 } else {
                                    Log.e(HiveMqttService.class.getSimpleName(), 
           throwable.getMessage());
                                }
                            });

Still i get an error saying "Call requires API level 24 (current min is 21): java.util.concurrent.CompletableFuture#whenComplete"

How can i resolve this?

**Comment by SgtSilvio** [comment]
This is actually just a warning of Android Studio that is displayed as an error.
Android Studio does not know that we backport the API, so it still thinks that the API can not be used with the minSdkVersion.
You can compile and run your app without any problems.
If you want to get rid of the warning, just add `@SuppressLint("NewApi")` to the method or class where you use the API.

**Comment by SgtSilvio** [comment]
I will update the documentation. Thanks for pointing it out.

I close this issue once the documentation is updated.

**Comment by SgtSilvio** [comment]
Updated the readme.
If this does not solve your problem, just comment and reopen this issue.
