### ISSUE TITLE
Android Gradle Plugin 7.0.0

### ISSUE THREAD

**Issue by george-theocharis** [SgtSilvio/android-retrofix#10]
Hey, awesome work with retrofix! 💪 

Since updating to Android Gradle Plugin 7.0.0, there is this warning that has come up: 
`Expected stack map table for method with non-linear control flow.`  
which as far as I know comes with the stricter verification rules for jdk 1_7 and above. In addition, the proposed solution I have found while researching is the below:
> Java version or bytecode instrumentation could both be blame. Usually, this means that a library that the application uses generates invalid bytecode that doesn't pass the stricter verification. So nothing else than reporting it as a bug to the library can be done by the developer.

Do you think there is anything that can be done by either side to fix this warning?

**Comment by HarisHoulis** [comment]
Hey, @SgtSilvio  thanks for the awesome work! Any news on this?

**Comment by SgtSilvio** [comment]
@george-theocharis @HarisHoulis released a new version 0.4.0 which works with Android Gradle Plugin 4.x and 7.x
