### ISSUE TITLE
NullPointer Exception on build

### ISSUE THREAD

**Issue by AswinpAshok** [SgtSilvio/android-retrofix#17]
Problem description : Build fails with NullPointer exception

    A problem occurred configuring project ':app'.
    java.lang.NullPointerException (no error message)
    .....
    Caused by: java.lang.NullPointerException
	at com.github.sgtsilvio.gradle.android.retrofix.RetroFixPlugin$apply$2.execute(RetroFixPlugin.kt:56)

RetroFixPlugin.kt expects `minSdkVersion` to be in `defaultConfig` block. But since my project have multiple app flavors and each of them have different `minSdkVersion`, it is not defined in `defaultConfig` block, it is defined inside `productFlavors` for each flavor.

How can this be fixed?

**Comment by SgtSilvio** [comment]
Hi @AswinpAshok 
Can you try setting the `minSdkVersion` in the `defaultConfig` to the minimum of all your flavors. If you define the `minSdkVersion` per flavor, it will be overwritten anyhow.

Can you share which flavors you are using? Do you want to apply android-retrofix only to a subset of flavors? This would be a new feature as currently, android-retrofix is applied to all variants.

**Comment by AswinpAshok** [comment]
@SgtSilvio Thanks. 

Setting the `minSdkVersion` in the `defaultConfig` works. I need retrofix for all flavors. So flavor specific implementation is not required. I have different flavors of app since one of those flavors depend on a library that demands a higher `minSdkVersion`.
