### ISSUE TITLE
Is it possible to support updateAndGet of AtomicInteger?

### ISSUE THREAD

**Issue by shanjunmei** [SgtSilvio/android-retrofix#19]
java.lang.NoSuchMethodError: No virtual method updateAndGet(Ljava9/util/function/IntUnaryOperator;)I in class Ljava/util/concurrent/atomic/AtomicInteger; or its super classes (declaration of 'java.util.concurrent.atomic.AtomicInteger' appears in /system/framework/core-libart.jar)

**Comment by SgtSilvio** [comment]
Should be solved by https://github.com/SgtSilvio/android-retrofix/issues/20
