### ISSUE TITLE
Can it work with the desugaring component of android studio? That component seems to already support the new methods in atomicInteger.

### ISSUE THREAD

**Issue by shanjunmei** [SgtSilvio/android-retrofix#20]
RT

**Comment by SgtSilvio** [comment]
Hi @shanjunmei 
Did you try to use Android's core library desugaring (https://developer.android.com/studio/write/java8-support#library-desugaring) together with retrofix?
When only backporting android-retrofuture and using Android's core library desugaring for backporting streams, it should work.
```
dependencies {
    retrofix("net.sourceforge.streamsupport:android-retrofuture:1.7.4")
    // don't use net.sourceforge.streamsupport:android-retrostreams:1.7.4 because this should be desugared
}
```

**Comment by shanjunmei** [comment]
> Hi @shanjunmei Did you try to use Android's core library desugaring (https://developer.android.com/studio/write/java8-support#library-desugaring) together with retrofix? When only backporting android-retrofuture and using Android's core library desugaring for backporting streams, it should work.
> 
> ```
> dependencies {
>     retrofix("net.sourceforge.streamsupport:android-retrofuture:1.7.4")
>     // don't use net.sourceforge.streamsupport:android-retrostreams:1.7.4 because this should be desugared
> }
> ```

yeah ,already solved ,thanks
