### ISSUE TITLE
Can't register com.github.sgtsilvio.gradle.android.retrofix.RetroFixClassVisitorFactory to instrument library dependencies.

### ISSUE THREAD

**Issue by android-ext** [SgtSilvio/android-retrofix#39]
Can't register com.github.sgtsilvio.gradle.android.retrofix.RetroFixClassVisitorFactory to instrument library dependencies.

**Comment by SgtSilvio** [comment]
Hi @android-ext 
can you provide more information like Android Gradle Plugin version, Android Studio version or parts of your build.gradle files?

**Comment by SgtSilvio** [comment]
I will close this issue because of missing information. Feel free to comment with additional information and I will reopen the issue.
