### ISSUE TITLE
Plugin is not available in repository

### ISSUE THREAD

**Issue by dafipentasys** [SgtSilvio/android-retrofix#4]
The Gradle Plugin Repository only contains the POM of the project, not the jar file needed to use it.

See:
https://plugins.gradle.org/m2/com/github/sgtsilvio/gradle/android-retrofix/com.github.sgtsilvio.gradle.android-retrofix.gradle.plugin/

**Comment by SgtSilvio** [comment]
Gradle plugins have a special structure for the artifacts.
The pom you linked only declares the dependency on the actual plugin.
Here is the link to the actual plugin with jar and sources:
https://plugins.gradle.org/m2/gradle/plugin/com/github/sgtsilvio/gradle/android-retrofix/0.3.0/
