### ISSUE TITLE
Cannot find META-INF.versions.9.module-info: module-info found in META-INF/versions/9/module-info.class

### ISSUE THREAD

**Issue by virgiliomagalhaes** [SgtSilvio/android-retrofix#7]
When i tried to create the release version i got this error:

> Task :[REDACTED]:mergeReleaseJavaResource
> Task :[REDACTED]:transformClassesWithAndroidRetroFixForRelease
> Task :[REDACTED]:transformClassesWithAndroidRetroFixForRelease FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':[REDACTED]:transformClassesWithAndroidRetroFixForRelease'.
> java.lang.RuntimeException: java.lang.RuntimeException: cannot find META-INF.versions.9.module-info: module-info found in META-INF/versions/9/module-info.class

**Comment by SgtSilvio** [comment]
@virgiliomagalhaes which version of android-retrofix are you using?
Can you provide your build script (or parts of it)?

**Comment by virgiliomagalhaes** [comment]
Im have been using last version of retrofix

**Comment by SgtSilvio** [comment]
@virgiliomagalhaes are you building on Windows?

**Comment by SgtSilvio** [comment]
Also could you find out where the module-info.class comes from, from a dependency? from your code?

**Comment by SgtSilvio** [comment]
@virgiliomagalhaes Please try out the new version 0.3.6, this could fix your issue.

**Comment by virgiliomagalhaes** [comment]
@SgtSilvio Hello Silvio, i fix this problem change the position of apply plugin after android.application plugin declaration. I had putted in a wrong position.

**Comment by SgtSilvio** [comment]
As this works now for you, I close this issue.
