### ISSUE TITLE
Support for 'com.android.library'

### ISSUE THREAD

**Issue by Nano222** [SgtSilvio/android-retrofix#8]
Hello,

using the retrofix plugin on 'com.android.library' instead of 'com.android.application' leads to an exception.
![image](https://user-images.githubusercontent.com/36038891/86923006-bd30c300-c12d-11ea-9363-6d01f39fff18.png)

Are there any plans to make the retrofix library also available for android library projects which use 'com.android.library'?

At the moment it can only be used for android application projects.

Works: ✅
apply plugin: 'com.android.application'
apply plugin: 'com.github.sgtsilvio.gradle.android-retrofix'

Fails: 🛑
apply plugin: 'com.android.library'
apply plugin: 'com.github.sgtsilvio.gradle.android-retrofix'

**Comment by SgtSilvio** [comment]
Hi @Nano222 
You do not need to apply the android retrofix plugin to your library.
Instead the android applications that use your library should apply the android retrofix plugin. The plugin then also transforms the classes provided by your library along with all other classes in the android application.

Does this help you?

**Comment by Nano222** [comment]
> Hi @Nano222
> You do not need to apply the android retrofix plugin to your library.
> Instead the android applications that use your library should apply the android retrofix plugin. The plugin then also transforms the classes provided by your library along with all other classes in the android application.
> 
> Does this help you?

Hi @SgtSilvio 

thx for your response.

Unfortunately we are not the developers of the app, we are only working on the library, so we can't control if they are using the "retrofix" plugin.
Thats why we need to address this issue on the library site.

**Comment by SgtSilvio** [comment]
Hi @Nano222 
> Thats why we need to address this issue on the library site.

Isn't it possible to document that users have to use the android retrofix plugin?

If the retrofix plugin would convert code that is exposed by your library, the app will not be able to use it as expected.
Are you needing the retrofix transform just for internal or your library?

**Comment by Nano222** [comment]
Hi @SgtSilvio,

sry for the late response.

> Are you needing the retrofix transform just for internals of your library?
Yes we need it only for internals. The mqtt connection will connect etc. automatically and everything is internal. Nothing gets exposed to the lib users.
Unfortunately it is not an option to add the retrofix to the app dependencies which uses the library.

**Comment by SgtSilvio** [comment]
@Nano222 the new version 0.4.0 should work for all Android plugins as it only uses BasePlugin/Extension.

**Comment by trustratch** [comment]
Hello @SgtSilvio. I am using retrofix to 0.4.1 and getting this error
`> com.android.builder.errors.EvalIssueException: Transforms with scopes '[SUB_PROJECTS, EXTERNAL_LIBRARIES]' cannot be applied to library projects.
`
When i use
`apply plugin: 'com.android.library'`
but it works normally with 
`apply plugin: 'com.android.application'`

**Comment by SgtSilvio** [comment]
> the new version 0.4.0 should work for all Android plugins

This message was actually wrong. It is not possible to support the android library plugin in a sensible way.
The reason for this is that a library ships with dependencies that it can't change. Android retrofix would only make sense for libraries without any dependencies or with all dependencies being repackaged into the library (which is not a good thing to do in general, but rather a hack; and it is also not a problem that can be solved in a general way by this plugin).

The new instrumentation API (used since v0.5.0) also prints the following error message which explains very clearly that it is not possible/intended to instrument code in libraries in a way android-retrofix does:

> Instrumenting library dependencies will have no effect on library consumers, move the dependencies instrumentation to be done in the consuming app or test component.

I hope this explanation is clear. Please use the android-retrofix plugin in the app that includes the library.
